import type { MediaItem } from '../types/media'

// This will be generated by a build script
export const mediaFiles: MediaItem[] = [
  { 
    id: 1, 
    type: 'image',
    src: '/media/gallery/technical-1.jpg',
    title: 'Technical Training',
    description: 'Players developing ball control skills'
  },
  // ... other files
]